project:
  type: website
  post-render:
    - "cp _redirects _site/"
    - "rm -rf _site/en/_site"
    - "rm -rf _site/fr/_site"
    - "rm -f _site/fr/_redirects"
    - "rm -f _site/en/_redirects"
profile:
  default: en
  group: [en, fr]
  
  
execute:
  freeze: true
