project:
  type: website
  output-dir: ./_site/en
  resources:
   - "files/"
website:
  title: "CanCOTS 2025"
  description: "Canadian Conference on Teaching Statistics"
  search: false
  navbar:
    pinned: true
    background: "#0072ce"
    right:
     - text: "FR"
       href: ../fr/index.html
announcement: 
    icon: info-circle
    dismissable: true
    content: "CanCOTS 2027 [takes place in Toronto, June 22-24, 2027](https://cancots2027.github.io/index.html)."
    type: primary
    position: below-navbar 
lang: en
format:
  html:
    theme:
       - html/custom.scss
